"""Add roleplay tables

Revision ID: 563e2f592f70
Revises: manual_stripe_sub_id
Create Date: 2025-09-19 05:18:11.678003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '563e2f592f70'
down_revision: Union[str, Sequence[str], None] = 'manual_stripe_sub_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roleplay_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('scenario_content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('emotion_types', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('age_range_min', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('age_range_max', sa.Integer(), server_default=sa.text('8'), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("color ~ '^#[0-9A-Fa-f]{6}$'", name='check_color_hex'),
    sa.CheckConstraint('age_range_max <= 12', name='check_age_range_max'),
    sa.CheckConstraint('age_range_min <= age_range_max', name='check_age_range_order'),
    sa.CheckConstraint('age_range_min >= 1', name='check_age_range_min'),
    sa.CheckConstraint('cardinality(emotion_types) > 0', name='check_emotion_types_nonempty'),
    sa.CheckConstraint('cardinality(keywords) > 0', name='check_keywords_nonempty'),
    sa.CheckConstraint('difficulty_level BETWEEN 1 AND 5', name='check_difficulty_level'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roleplay_scenarios_is_active', 'roleplay_scenarios', ['is_active'], unique=False)
    op.create_table('roleplay_advice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('emotion_id', sa.String(length=50), nullable=False),
    sa.Column('advice_text', sa.Text(), nullable=False),
    sa.Column('advice_type', sa.String(length=50), server_default=sa.text("'general'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("advice_type IN ('general', 'breathing', 'communication')", name='check_advice_type'),
    sa.ForeignKeyConstraint(['scenario_id'], ['roleplay_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roleplay_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('emotion_log_id', sa.UUID(), nullable=True),
    sa.Column('selected_emotion_id', sa.String(length=50), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.Column('completion_status', sa.String(length=20), server_default=sa.text("'started'"), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(completion_status <> 'completed') OR (completed_at IS NOT NULL)", name='check_completed_has_timestamp'),
    sa.CheckConstraint("completion_status IN ('started', 'completed', 'abandoned')", name='check_completion_status'),
    sa.CheckConstraint('session_duration IS NULL OR session_duration >= 0', name='check_duration_nonnegative'),
    sa.CheckConstraint('user_rating BETWEEN 1 AND 5', name='check_user_rating'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emotion_log_id'], ['emotion_logs.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['roleplay_scenarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roleplay_sessions_child', 'roleplay_sessions', ['child_id'], unique=False)
    op.create_index('ix_roleplay_sessions_user', 'roleplay_sessions', ['user_id'], unique=False)
    op.alter_column('emotion_logs', 'audio_file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emotion_logs', 'audio_file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_roleplay_sessions_user', table_name='roleplay_sessions')
    op.drop_index('ix_roleplay_sessions_child', table_name='roleplay_sessions')
    op.drop_table('roleplay_sessions')
    op.drop_table('roleplay_advice')
    op.drop_index('ix_roleplay_scenarios_is_active', table_name='roleplay_scenarios')
    op.drop_table('roleplay_scenarios')
    # ### end Alembic commands ###